"""The assembler, checked against SQL a person wrote.

Each question below appears twice: once as SQL written by hand against the
new coded schema, and once as terms resolved through the definitions layer
and assembled. The test is that they return the same patients.

**The hand-written half is the baseline and must stay hand-written.** A
baseline generated by the thing it is supposed to check proves only that the
code is consistent with itself. If the assembler grows a bug, these queries
are the fixed point that notices.

No LLM is involved anywhere in this file. The terms are passed in directly —
this is the deterministic half the model's own term choice sits on top of.
"""

import pytest
from sqlalchemy import text

from app.clinical.assembler import medication_aggregate_query, patient_query
from app.clinical.predicates import InvalidPredicateError
from app.services import definition_service
from tests.support.fixture import (
    CONTEXTUAL_SEVERE_ALIVE,
    ELDERLY_HIGH_RISK_NO_RENAL,
    FIXTURE_TODAY,
    RUNNING_EXAMPLE_CORE,
    RUNNING_EXAMPLE_MODERATE,
    RUNNING_EXAMPLE_NOT_SEVERE,
)

TODAY = FIXTURE_TODAY


@pytest.fixture
async def seeded(session):
    # The clinical dataset is seeded once for the whole session — see
    # tests/integration/conftest.py — and every test in this file only reads.
    return session


async def _by_hand(session, sql: str) -> set[str]:
    rows = await session.execute(text(sql), {"today": TODAY})
    return {row[0] for row in rows}


async def _by_assembly(session, *terms: str) -> set[str]:
    resolution = await definition_service.resolve_terms(session, terms=list(terms))
    assert resolution.is_complete, (
        f"unresolved={resolution.unresolved} invalid={resolution.invalid}"
    )
    query = patient_query([resolved.predicate for resolved in resolution.resolved], today=TODAY)
    rows = await session.execute(query)
    return {row.source_id for row in rows}


# --- the running example -----------------------------------------------------

RUNNING_EXAMPLE_SQL = """
    select p.source_id
    from patients p
    where (
        select o.value_numeric from observations o
        where o.patient_id = p.id and o.code = '33914-3'
          and o.unit in ('mL/min/{1.73_m2}', 'mL/min') and o.value_numeric is not null
        order by o.taken_at desc limit 1
    ) < 60
    and exists (
        select 1 from prescriptions rx
        join medications m on m.id = rx.medication_id
        join medication_annotations ma on ma.code = m.code
        where rx.patient_id = p.id and rx.end_date is null
          and ma.attribute = 'nephrotoxic_risk' and ma.value in ('high', 'moderate')
    )
"""


async def test_the_running_example_matches_the_hand_written_query(seeded):
    by_hand = await _by_hand(seeded, RUNNING_EXAMPLE_SQL)
    by_assembly = await _by_assembly(seeded, "impaired renal function", "nephrotoxic medication")

    assert by_hand, "the baseline returned nothing — the fixture is wrong, not the assembler"
    assert by_assembly == by_hand


async def test_the_running_example_contains_the_anchors_it_should(seeded):
    """Belt and braces: the two queries could agree and both be wrong."""
    ids = await _by_assembly(seeded, "impaired renal function", "nephrotoxic medication")

    assert {RUNNING_EXAMPLE_CORE, RUNNING_EXAMPLE_MODERATE, RUNNING_EXAMPLE_NOT_SEVERE} <= ids
    assert CONTEXTUAL_SEVERE_ALIVE not in ids
    assert ELDERLY_HIGH_RISK_NO_RENAL not in ids


# --- age plus medication -----------------------------------------------------

ELDERLY_HIGH_RISK_SQL = """
    select p.source_id
    from patients p
    where date_part('year', age(coalesce(p.death_date, :today), p.birth_date)) >= 65
    and exists (
        select 1 from prescriptions rx
        join medications m on m.id = rx.medication_id
        join medication_annotations ma on ma.code = m.code
        where rx.patient_id = p.id
          and ma.attribute = 'nephrotoxic_risk' and ma.value = 'high'
    )
"""


async def test_elderly_on_a_high_risk_nephrotoxin(seeded):
    by_hand = await _by_hand(seeded, ELDERLY_HIGH_RISK_SQL)
    by_assembly = await _by_assembly(seeded, "elderly", "high-risk nephrotoxic medication")

    assert by_hand
    assert by_assembly == by_hand
    # Cisplatin, closed in 2005 — `high-risk nephrotoxic medication` reads
    # `exposure: ever`, so a course closed for two decades still counts.
    assert ELDERLY_HIGH_RISK_NO_RENAL in by_assembly


# --- lab plus drug class -----------------------------------------------------


async def test_hyperkalemia_on_a_renin_angiotensin_blocker_is_a_real_empty_answer(seeded):
    """Zero patients in this dataset clear 5.5 mmol/L potassium. The threshold
    stays, on purpose, as the model-check demo case — tuning it to manufacture
    a match would be tuning a clinical threshold to make a demo look better.
    So this is not "the query is broken," it is "the answer is empty," and the
    test is that both the hand-written and assembled queries agree on
    that rather than one of them silently returning something.
    """
    by_hand_sql = """
        select p.source_id
        from patients p
        where (
            select o.value_numeric from observations o
            where o.patient_id = p.id and o.code in ('2823-3', '6298-4')
              and o.unit = 'mmol/L' and o.value_numeric is not null
            order by o.taken_at desc limit 1
        ) > 5.5
        and exists (
            select 1 from prescriptions rx
            join medications m on m.id = rx.medication_id
            join medication_annotations ma on ma.code = m.code
            where rx.patient_id = p.id and rx.end_date is null
              and ma.attribute = 'nephrotoxic_risk' and ma.value = 'contextual'
        )
    """
    by_hand = await _by_hand(seeded, by_hand_sql)
    by_assembly = await _by_assembly(seeded, "hyperkalemia", "renin-angiotensin blocker")

    assert by_hand == set()
    assert by_assembly == set()


async def test_renin_angiotensin_blocker_reaches_the_contextual_tier(seeded):
    """The term `hyperkalemia` needs a real match against, on its own: proof
    that `renin-angiotensin blocker` resolves real patients even though
    `nephrotoxic medication` deliberately excludes the same drugs.
    """
    by_assembly = await _by_assembly(seeded, "renin-angiotensin blocker")
    assert CONTEXTUAL_SEVERE_ALIVE in by_assembly
    # And this anchor is excluded from the flat nephrotoxic term for exactly
    # the reason it is an anchor at all — see test_seed.py.
    nephrotoxic = await _by_assembly(seeded, "nephrotoxic medication")
    assert CONTEXTUAL_SEVERE_ALIVE not in nephrotoxic


# --- a single predicate ------------------------------------------------------

SEVERE_SQL = """
    select p.source_id
    from patients p
    where (
        select o.value_numeric from observations o
        where o.patient_id = p.id and o.code = '33914-3'
          and o.unit in ('mL/min/{1.73_m2}', 'mL/min') and o.value_numeric is not null
        order by o.taken_at desc limit 1
    ) < 30
"""


async def test_a_single_term_question(seeded):
    by_hand = await _by_hand(seeded, SEVERE_SQL)
    by_assembly = await _by_assembly(seeded, "severely impaired renal function")

    assert by_hand
    assert by_assembly == by_hand


async def test_severe_is_a_subset_of_impaired(seeded):
    """The two renal terms must nest. If they cross, one threshold is backwards."""
    severe = await _by_assembly(seeded, "severely impaired renal function")
    impaired = await _by_assembly(seeded, "impaired renal function")
    assert severe < impaired


# --- resolution --------------------------------------------------------------


async def test_a_synonym_resolves_to_its_canonical_term(seeded):
    resolution = await definition_service.resolve_terms(seeded, terms=["CKD", "  low  EGFR "])
    assert resolution.is_complete
    assert {r.term for r in resolution.resolved} == {"impaired renal function"}
    assert {r.matched_on for r in resolution.resolved} == {"CKD", "  low  EGFR "}


async def test_an_unknown_term_does_not_resolve(seeded):
    """No fuzzy fallback. A near-miss answers a question nobody asked."""
    resolution = await definition_service.resolve_terms(seeded, terms=["hepatic impairment"])
    assert not resolution.is_complete
    assert resolution.unresolved == ("hepatic impairment",)
    assert resolution.resolved == ()


async def test_a_partial_resolution_is_not_complete(seeded):
    """The dangerous case: one leg resolves, one does not.

    Assembling anyway would drop a filter and return more patients than were
    asked about — and look entirely plausible doing it.
    """
    resolution = await definition_service.resolve_terms(
        seeded, terms=["impaired renal function", "wildly invented term"]
    )
    assert resolution.resolved
    assert not resolution.is_complete


async def test_a_composed_term_matches_the_terms_anded_by_hand(seeded):
    """`renal risk on a nephrotoxin` is `all_of(impaired renal function,
    nephrotoxic medication)` in the table — proving composition is not just
    parseable but produces the same cohort as ANDing the two terms directly."""
    composed = await _by_assembly(seeded, "renal risk on a nephrotoxin")
    anded = await _by_assembly(seeded, "impaired renal function", "nephrotoxic medication")
    assert composed == anded


# --- medication-entity aggregate ---------------------------------------------

NEPHROTOXIC_BY_NAME_SQL = """
    select m.display as medication, count(distinct rx.patient_id) as patients
    from prescriptions rx
    join medications m on m.id = rx.medication_id
    join medication_annotations ma on ma.code = m.code
    where rx.patient_id in (
        select p.id from patients p
        where date_part('year', age(coalesce(p.death_date, :today), p.birth_date)) >= 65
    )
    and ma.attribute = 'nephrotoxic_risk' and ma.value in ('high', 'moderate')
    and rx.end_date is null
    group by m.display
"""


async def _resolve_measure(session, term: str) -> definition_service.ResolvedMeasure:
    resolution = await definition_service.resolve_measures(session, names=[term])
    assert resolution.is_complete, f"unresolved={resolution.unresolved}"
    return resolution.resolved[0]


async def _resolve_dimension(session, term: str) -> definition_service.ResolvedDimension:
    resolution = await definition_service.resolve_dimensions(session, names=[term])
    assert resolution.is_complete, f"unresolved={resolution.unresolved}"
    return resolution.resolved[0]


async def test_which_nephrotoxins_are_most_prescribed_among_the_elderly(seeded):
    """SEMANTIC_LAYER.md § 11's own named example: a question about drugs, not
    patients. `elderly` is still an ordinary patient-level filter — the only
    new thing is the dimension, which is why this belongs beside the
    patient-scoped cases above rather than off on its own."""
    by_hand = {}
    for row in await seeded.execute(text(NEPHROTOXIC_BY_NAME_SQL), {"today": TODAY}):
        by_hand[row.medication] = row.patients

    terms = await definition_service.resolve_terms(seeded, terms=["elderly"])
    measure = await _resolve_measure(seeded, "patient count")
    dimension = await _resolve_dimension(seeded, "nephrotoxic medication name")

    query = medication_aggregate_query(
        [r.predicate for r in terms.resolved],
        measures=[(measure.term, measure.measure)],
        dimensions=[(dimension.term, dimension.dimension)],
        today=TODAY,
    )
    by_assembly = {
        row._mapping["nephrotoxic medication name"]: row._mapping["patient count"]
        for row in await seeded.execute(query)
    }

    assert by_hand, "the baseline returned nothing — the fixture is wrong, not the assembler"
    assert by_assembly == by_hand


async def test_a_medication_dimension_refuses_an_observation_measure(seeded):
    """There is no per-medication eGFR to average — only a patient count is a
    meaningful thing to report grouped by drug name."""
    dimension = await _resolve_dimension(seeded, "nephrotoxic medication name")
    egfr = await _resolve_measure(seeded, "average eGFR")

    with pytest.raises(InvalidPredicateError, match="only a patient count"):
        medication_aggregate_query(
            [],
            measures=[(egfr.term, egfr.measure)],
            dimensions=[(dimension.term, dimension.dimension)],
            today=TODAY,
        )


async def test_a_patient_dimension_is_refused_by_the_medication_query(seeded):
    """`aggregate_query` and `medication_aggregate_query` each own one entity;
    a patient-scoped dimension handed to the medication one is refused rather
    than silently answering a query nobody asked."""
    measure = await _resolve_measure(seeded, "patient count")
    dimension = await _resolve_dimension(seeded, "sex")

    with pytest.raises(InvalidPredicateError, match="medication_name dimension"):
        medication_aggregate_query(
            [],
            measures=[(measure.term, measure.measure)],
            dimensions=[(dimension.term, dimension.dimension)],
            today=TODAY,
        )


# --- failing closed ----------------------------------------------------------


def test_no_predicates_is_refused():
    """An unfiltered query is every patient in the hospital."""
    with pytest.raises(InvalidPredicateError, match="no predicates"):
        patient_query([], today=TODAY)


async def test_values_are_bound_not_interpolated(seeded):
    """The structural claim the definitions layer rests on.

    The compiled SQL must carry placeholders, not literals. If a threshold
    ever appears inline in the statement text, something is building SQL by
    concatenation and the injection argument for structured `logic` is void.
    """
    resolution = await definition_service.resolve_terms(seeded, terms=["impaired renal function"])
    query = patient_query([r.predicate for r in resolution.resolved], today=TODAY)
    compiled = str(query.compile())

    assert "60" not in compiled
    assert ":" in compiled
