"""The seed, against a real database.

The unit suite already proves the definitions are internally consistent. What
needs a Postgres is whether the *data* lands correctly: that the constraints
accept a real Synthea export, and that each anchor patient ends up with the
clinical properties `scripts/build-test-fixture.py` picked it for. Those
properties are what the running example's expected answer rests on, so they
are asserted here rather than eyeballed once and assumed.
"""

import csv
import gzip

import pytest
from sqlalchemy import text

from app.services import seed_service
from tests.support.fixture import (
    CONTEXTUAL_SEVERE_ALIVE,
    CONTROL_ONE,
    CONTROL_TWO,
    ELDERLY_HIGH_RISK_NO_RENAL,
    EXCLUDED_COURSE_ENDED_ALIVE,
    EXCLUDED_COURSE_ENDED_DECEASED,
    FIXTURE_SOURCE,
    RECENT_EXPOSURE_NOT_ACTIVE,
    RUNNING_EXAMPLE_CORE,
    RUNNING_EXAMPLE_MODERATE,
    RUNNING_EXAMPLE_NOT_SEVERE,
    UNMEASURED_EGFR_HIGH_TIER_EVER,
)

# The two legs of "patients on a nephrotoxic medication with impaired kidney
# function", as plain SQL against the new coded schema. Deliberately
# hand-written: `app/clinical/assembler.py` is supposed to reproduce this, and
# a baseline generated by the thing it is meant to check is not a baseline.
#
# `coalesce(..., false)` on the renal leg matters: a patient with no eGFR on
# record has no row in `latest_egfr` at all, and that must read as "not
# impaired" (excluded), the same way the assembler's scalar-subquery
# threshold does when the subquery returns NULL — not as a SQL NULL that
# quietly drops out of comparisons.
ANCHOR_LEGS = text("""
    with latest_egfr as (
        select distinct on (patient_id) patient_id, value_numeric
        from observations
        where code = '33914-3'
          and unit in ('mL/min/{1.73_m2}', 'mL/min')
          and value_numeric is not null
        order by patient_id, taken_at desc
    )
    select p.source_id,
           coalesce(e.value_numeric < 60, false) as renal_leg,
           exists (
               select 1
               from prescriptions rx
               join medications m on m.id = rx.medication_id
               join medication_annotations ma on ma.code = m.code
               where rx.patient_id = p.id
                 and rx.end_date is null
                 and ma.attribute = 'nephrotoxic_risk'
                 and ma.value in ('high', 'moderate')
           ) as drug_leg
    from patients p
    left join latest_egfr e on e.patient_id = p.id
    where p.source_id = any(:anchor_ids)
""")

# source_id -> (renal_leg, drug_leg), hand-verified against the evidence in
# scripts/build-test-fixture.py's ANCHORS dict before this file was written —
# not generated by running the assembler.
ANCHOR_LEGS_EXPECTED: dict[str, tuple[bool, bool]] = {
    RUNNING_EXAMPLE_CORE: (True, True),
    RUNNING_EXAMPLE_MODERATE: (True, True),
    RUNNING_EXAMPLE_NOT_SEVERE: (True, True),
    EXCLUDED_COURSE_ENDED_DECEASED: (True, False),
    EXCLUDED_COURSE_ENDED_ALIVE: (True, False),
    CONTEXTUAL_SEVERE_ALIVE: (True, False),
    RECENT_EXPOSURE_NOT_ACTIVE: (True, False),
    UNMEASURED_EGFR_HIGH_TIER_EVER: (False, False),
    ELDERLY_HIGH_RISK_NO_RENAL: (False, False),
    CONTROL_ONE: (False, False),
    CONTROL_TWO: (False, False),
}


def _fixture_row_count(name: str) -> int:
    """An independent count straight off the committed CSV, so `summary.
    patients`/`.medications` are checked against the source file rather than
    against another read of the same seed that produced them."""
    with gzip.open(FIXTURE_SOURCE / f"{name}.csv.gz", "rt", newline="", encoding="utf-8") as handle:
        return sum(1 for _ in csv.DictReader(handle))


@pytest.fixture
async def seeded(session):
    await seed_service.seed_all(session, source=FIXTURE_SOURCE, reset=True)
    return session


async def test_seeding_twice_is_a_no_op_without_reset(seeded):
    summary = await seed_service.seed_all(seeded, source=FIXTURE_SOURCE)
    assert summary.skipped


async def test_reset_reloads_rather_than_duplicating(seeded):
    summary = await seed_service.seed_all(seeded, source=FIXTURE_SOURCE, reset=True)
    assert not summary.skipped
    assert summary.patients == _fixture_row_count("patients")
    # Medications land one row per distinct RxNorm code, not one per source
    # row — several patients share a drug, and one patient refills the same
    # drug many times. `_fixture_row_count` counts source rows, so this
    # checks the loader actually deduplicates rather than checking a number.
    distinct_codes = set()
    with gzip.open(
        FIXTURE_SOURCE / "medications.csv.gz", "rt", newline="", encoding="utf-8"
    ) as handle:
        for row in csv.DictReader(handle):
            distinct_codes.add(row["CODE"])
    assert summary.medications == len(distinct_codes)


async def test_every_anchor_lands_on_the_side_it_was_designed_for(seeded):
    """The expected answer to the running example, asserted patient by patient.

    A failure here names the anchor, because "8 rows, expected 9" is not a
    debuggable message — the useful question is always *which* patient moved
    and which leg moved it. See `scripts/build-test-fixture.py`'s `ANCHORS`
    dict for the clinical reasoning behind each one.
    """
    rows = (await seeded.execute(ANCHOR_LEGS, {"anchor_ids": list(ANCHOR_LEGS_EXPECTED)})).all()
    found = {source_id for source_id, _, _ in rows}
    missing = set(ANCHOR_LEGS_EXPECTED) - found
    assert not missing, f"anchor(s) not in the seeded fixture: {missing}"

    for source_id, renal_leg, drug_leg in rows:
        expected_renal, expected_drug = ANCHOR_LEGS_EXPECTED[source_id]
        assert (renal_leg, drug_leg) == (expected_renal, expected_drug), (
            f"{source_id} expected renal_leg={expected_renal} drug_leg={expected_drug}, "
            f"got renal_leg={renal_leg} drug_leg={drug_leg}"
        )


async def test_the_contextual_tier_is_excluded(seeded):
    """The discriminating case, asserted on its own so it cannot be lost in a
    loop over every anchor.

    `CONTEXTUAL_SEVERE_ALIVE` has severely impaired kidney function and is
    actively on losartan — annotated, but tier `contextual`, not `high` or
    `moderate`. A flat nephrotoxic boolean would return this patient; the
    tiered definition must not.
    """
    row = (
        (
            await seeded.execute(
                text("""
                select ma.value
                from prescriptions rx
                join medications m on m.id = rx.medication_id
                join medication_annotations ma on ma.code = m.code
                join patients p on p.id = rx.patient_id
                where p.source_id = :source_id
                  and rx.end_date is null
                  and ma.attribute = 'nephrotoxic_risk'
            """),
                {"source_id": CONTEXTUAL_SEVERE_ALIVE},
            )
        )
        .scalars()
        .all()
    )
    assert row == ["contextual"], (
        "this anchor is only useful if its one active annotated prescription is "
        f"tier 'contextual' — got {row}"
    )
    assert ANCHOR_LEGS_EXPECTED[CONTEXTUAL_SEVERE_ALIVE] == (True, False)


async def test_the_audit_log_is_not_touched_by_a_reset(seeded):
    """An audit trail a maintenance command can empty is not an audit trail."""
    await seeded.execute(
        text("""
            insert into query_audit (asked_by, raw_question, outcome)
            values ('tester', 'a question that was asked', 'answered')
        """)
    )
    await seeded.commit()

    await seed_service.seed_all(seeded, source=FIXTURE_SOURCE, reset=True)

    remaining = (await seeded.execute(text("select count(*) from query_audit"))).scalar_one()
    assert remaining == 1
