"""synthea coded observations, medication annotations, semantic model

Revision ID: 6eb388c40933
Revises: 7a7b85a3f28c
Create Date: 2026-09-21 23:54:12.350921+00:00

The hand-rolled synthetic dataset (`patients`, `medications`,
`prescriptions`, `labs`) is replaced by a Synthea export, loaded through
`python -m app.seed`. `labs` is dropped outright — `observations` replaces
it — and `patients`/`medications` gain Synthea's own identifiers as required
columns, which a row from the old seed does not have.

**That is why this migration starts by emptying those three tables.** They
hold nothing but regenerable synthetic data, and `ALTER TABLE ... ADD COLUMN
... NOT NULL` with no default fails outright against an existing row anyway —
autogenerate cannot see that this is a dataset swap, not a column added to
data worth keeping, so the truncate is hand-added rather than something
`--autogenerate` produced. Read AGENTS.md's note on this migration before
touching it again: `docker compose up` reseeds automatically, but any other
deployment applying this needs `python -m app.seed` run again afterwards.
`query_audit` and `clinical_definitions` are untouched here — old audit rows
and old definitions survive; the seed rewrites the definitions afterward
through `definition_service.create_definition`, which is where their history
starts over.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql
revision: str = '6eb388c40933'
down_revision: str | None = '7a7b85a3f28c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added — see the module docstring. Must run before the NOT NULL
    # column additions below, which would otherwise fail against any row the
    # old synthetic seed left behind. CASCADE reaches `labs` and
    # `prescriptions` through their foreign keys to these two tables.
    op.execute("truncate table patients, medications restart identity cascade")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_definition_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action in ('created', 'updated', 'deleted')", name='clinical_definition_history_action_check'),
    sa.CheckConstraint('length(trim(change_reason)) > 0', name='clinical_definition_history_reason_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'version', 'action', name='clinical_definition_history_version_key')
    )
    op.create_index('clinical_definition_history_definition_idx', 'clinical_definition_history', ['definition_id', 'version'], unique=False)
    op.create_table('dataset_meta',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('patient_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('attribute', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(rationale)) > 0', name='medication_annotations_rationale_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'attribute', name='medication_annotations_code_attribute_key')
    )
    op.create_index('medication_annotations_attribute_idx', 'medication_annotations', ['attribute', 'value'], unique=False)
    op.create_table('observation_catalog',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('display', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('units', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('patient_count', sa.Integer(), nullable=False),
    sa.Column('is_numeric', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('saved_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('measures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('group_by', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(terms) = 'array'", name='saved_questions_terms_check'),
    sa.CheckConstraint('length(trim(name)) > 0', name='saved_questions_name_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('saved_questions_user_idx', 'saved_questions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('scope_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(roles) = 'array'", name='user_roles_roles_check'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('display', sa.Text(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value_numeric is not null or value_text is not null', name='observations_has_a_value_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('observations_code_idx', 'observations', ['code'], unique=False)
    op.create_index('observations_patient_code_taken_idx', 'observations', ['patient_id', 'code', sa.literal_column('taken_at DESC')], unique=False)
    op.drop_index(op.f('labs_patient_test_taken_idx'), table_name='labs')
    op.drop_table('labs')
    op.add_column('clinical_definitions', sa.Column('kind', sa.Text(), server_default=sa.text("'filter'"), nullable=False))
    op.add_column('clinical_definitions', sa.Column('status', sa.Text(), server_default=sa.text("'published'"), nullable=False))
    op.add_column('clinical_definitions', sa.Column('owner', sa.Text(), nullable=True))
    op.add_column('clinical_definitions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clinical_definitions', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('clinical_definitions', sa.Column('updated_by', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('code', sa.Text(), nullable=False))
    op.add_column('medications', sa.Column('system', sa.Text(), nullable=False))
    op.add_column('medications', sa.Column('display', sa.Text(), nullable=False))
    op.drop_constraint(op.f('medications_name_key'), 'medications', type_='unique')
    op.drop_index(op.f('medications_nephrotoxic_idx'), table_name='medications', postgresql_where='(nephrotoxic_risk IS NOT NULL)')
    op.create_index('medications_code_idx', 'medications', ['code'], unique=False)
    op.create_unique_constraint(None, 'medications', ['code'])
    op.drop_column('medications', 'drug_class')
    op.drop_column('medications', 'risk_rationale')
    op.drop_column('medications', 'name')
    op.drop_column('medications', 'nephrotoxic_risk')
    op.add_column('patients', sa.Column('source_id', sa.Text(), nullable=False))
    op.add_column('patients', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('patients', sa.Column('death_date', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('race', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('ethnicity', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('ssn', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('drivers', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('passport', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    op.drop_constraint(op.f('patients_mrn_key'), 'patients', type_='unique')
    op.create_index('patients_birth_date_idx', 'patients', ['birth_date'], unique=False)
    op.create_unique_constraint(None, 'patients', ['source_id'])
    op.drop_column('patients', 'mrn')
    op.drop_column('patients', 'date_of_birth')
    op.add_column('prescriptions', sa.Column('reason_display', sa.Text(), nullable=True))
    op.drop_index(op.f('prescriptions_active_patient_idx'), table_name='prescriptions', postgresql_where='(end_date IS NULL)')
    op.create_index('prescriptions_end_date_idx', 'prescriptions', ['end_date'], unique=False)
    op.create_index('prescriptions_patient_idx', 'prescriptions', ['patient_id'], unique=False)
    op.drop_column('prescriptions', 'dose')
    op.add_column('query_audit', sa.Column('via', sa.Text(), server_default='tool', nullable=False))
    op.add_column('query_audit', sa.Column('definition_versions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('query_audit', sa.Column('measures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('query_audit', sa.Column('group_by', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###

    # Hand-added — autogenerate does not diff CHECK constraint bodies, only
    # their presence by name (env.py's own docstring already says so for the
    # rename case; this is the same blind spot for a value list). It also did
    # not emit a CHECK for `kind`, `status` or `version` on `clinical_
    # definitions` at all, or for `via` on `query_audit`, despite those
    # columns being new in this migration — new columns get a CHECK only when
    # the table itself is newly created, not when it is altered. Found by
    # actually seeding: `_insert_definitions` failed on the very first row
    # with `clinical_definitions_entity_check` still listing 'lab' instead of
    # 'observation'. Verified against every `CheckConstraint` in `models.py`
    # rather than trusting that finding one meant it was the only one.
    op.drop_constraint('clinical_definitions_entity_check', 'clinical_definitions', type_='check')
    op.create_check_constraint(
        'clinical_definitions_entity_check',
        'clinical_definitions',
        "entity in ('patient', 'medication', 'observation')",
    )
    op.create_check_constraint(
        'clinical_definitions_kind_check',
        'clinical_definitions',
        "kind in ('filter', 'measure', 'dimension')",
    )
    op.create_check_constraint(
        'clinical_definitions_status_check',
        'clinical_definitions',
        "status in ('draft', 'published', 'deprecated')",
    )
    op.create_check_constraint(
        'clinical_definitions_version_check', 'clinical_definitions', 'version >= 1'
    )
    op.create_check_constraint(
        'query_audit_via_check',
        'query_audit',
        "via in ('tool', 'cohort', 'explain', 'export', 'preview')",
    )


def downgrade() -> None:
    # Reverses the hand-added block at the end of upgrade(), in the opposite
    # order, before the autogenerated block starts undoing the columns those
    # constraints are on.
    op.drop_constraint('query_audit_via_check', 'query_audit', type_='check')
    op.drop_constraint('clinical_definitions_version_check', 'clinical_definitions', type_='check')
    op.drop_constraint('clinical_definitions_status_check', 'clinical_definitions', type_='check')
    op.drop_constraint('clinical_definitions_kind_check', 'clinical_definitions', type_='check')
    op.drop_constraint('clinical_definitions_entity_check', 'clinical_definitions', type_='check')
    op.create_check_constraint(
        'clinical_definitions_entity_check',
        'clinical_definitions',
        "entity in ('patient', 'medication', 'lab')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_audit', 'group_by')
    op.drop_column('query_audit', 'measures')
    op.drop_column('query_audit', 'definition_versions')
    op.drop_column('query_audit', 'via')
    op.add_column('prescriptions', sa.Column('dose', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('prescriptions_patient_idx', table_name='prescriptions')
    op.drop_index('prescriptions_end_date_idx', table_name='prescriptions')
    op.create_index(op.f('prescriptions_active_patient_idx'), 'prescriptions', ['patient_id'], unique=False, postgresql_where='(end_date IS NULL)')
    op.drop_column('prescriptions', 'reason_display')
    op.add_column('patients', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('mrn', sa.TEXT(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_index('patients_birth_date_idx', table_name='patients')
    op.create_unique_constraint(op.f('patients_mrn_key'), 'patients', ['mrn'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'passport')
    op.drop_column('patients', 'drivers')
    op.drop_column('patients', 'ssn')
    op.drop_column('patients', 'city')
    op.drop_column('patients', 'state')
    op.drop_column('patients', 'ethnicity')
    op.drop_column('patients', 'race')
    op.drop_column('patients', 'death_date')
    op.drop_column('patients', 'birth_date')
    op.drop_column('patients', 'source_id')
    op.add_column('medications', sa.Column('nephrotoxic_risk', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('risk_rationale', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('drug_class', sa.TEXT(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'medications', type_='unique')
    op.drop_index('medications_code_idx', table_name='medications')
    op.create_index(op.f('medications_nephrotoxic_idx'), 'medications', ['nephrotoxic_risk'], unique=False, postgresql_where='(nephrotoxic_risk IS NOT NULL)')
    op.create_unique_constraint(op.f('medications_name_key'), 'medications', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('medications', 'display')
    op.drop_column('medications', 'system')
    op.drop_column('medications', 'code')
    op.drop_column('clinical_definitions', 'updated_by')
    op.drop_column('clinical_definitions', 'version')
    op.drop_column('clinical_definitions', 'reviewed_at')
    op.drop_column('clinical_definitions', 'owner')
    op.drop_column('clinical_definitions', 'status')
    op.drop_column('clinical_definitions', 'kind')
    op.create_table('labs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('taken_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("test_name = ANY (ARRAY['egfr'::text, 'creatinine'::text, 'potassium'::text, 'bun'::text])", name=op.f('labs_test_name_check')),
    sa.CheckConstraint('value >= 0::numeric', name=op.f('labs_value_nonnegative_check')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('labs_patient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('labs_pkey'))
    )
    op.create_index(op.f('labs_patient_test_taken_idx'), 'labs', ['patient_id', 'test_name', sa.literal_column('taken_at DESC')], unique=False)
    op.drop_index('observations_patient_code_taken_idx', table_name='observations')
    op.drop_index('observations_code_idx', table_name='observations')
    op.drop_table('observations')
    op.drop_table('user_roles')
    op.drop_index('saved_questions_user_idx', table_name='saved_questions')
    op.drop_table('saved_questions')
    op.drop_table('observation_catalog')
    op.drop_index('medication_annotations_attribute_idx', table_name='medication_annotations')
    op.drop_table('medication_annotations')
    op.drop_table('dataset_meta')
    op.drop_index('clinical_definition_history_definition_idx', table_name='clinical_definition_history')
    op.drop_table('clinical_definition_history')
    # ### end Alembic commands ###
