"""add invariants to clinical definitions

Revision ID: 8e146dede379
Revises: 6eb388c40933
Create Date: 2026-09-22 20:17:44.579171+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8e146dede379"
down_revision: str | None = "6eb388c40933"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinical_definition_history",
        sa.Column(
            "invariants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "clinical_definitions",
        sa.Column(
            "invariants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clinical_definitions", "invariants")
    op.drop_column("clinical_definition_history", "invariants")
    # ### end Alembic commands ###
