"""add request_id to tasks

Revision ID: 04690bc99e07
Revises: a792650c543c
Create Date: 2026-09-17 20:52:46.433605+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '04690bc99e07'
down_revision: str | None = 'a792650c543c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('request_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'request_id')
    # ### end Alembic commands ###
