"""conversation pinning, archiving, and custom titles

Revision ID: c36eb1e4ba06
Revises: 04690bc99e07
Create Date: 2026-09-18 15:30:35.134356+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c36eb1e4ba06'
down_revision: str | None = '04690bc99e07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title_custom', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('conversations', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # NOT autogenerated, and the reason is worth knowing: Alembic compares an
    # index by name and columns, and does not look at its WHERE clause at all.
    # The model now declares this one `postgresql_where=archived_at is null` —
    # autogenerate saw the same name over the same columns, concluded nothing
    # had changed, and emitted nothing. A partial index that only exists in
    # models.py is an index that does not exist.
    #
    # Drop and recreate rather than alter: Postgres has no ALTER INDEX for a
    # predicate.
    op.drop_index('conversations_user_updated_idx', table_name='conversations')
    op.create_index(
        'conversations_user_updated_idx',
        'conversations',
        ['user_id', sa.literal_column('updated_at DESC')],
        unique=False,
        postgresql_where=sa.text('archived_at is null'),
    )


def downgrade() -> None:
    op.drop_index('conversations_user_updated_idx', table_name='conversations')
    op.create_index(
        'conversations_user_updated_idx',
        'conversations',
        ['user_id', sa.literal_column('updated_at DESC')],
        unique=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived_at')
    op.drop_column('conversations', 'pinned_at')
    op.drop_column('conversations', 'title_custom')
    # ### end Alembic commands ###
