"""initial schema

Revision ID: a792650c543c
Revises: 
Create Date: 2026-09-17 20:34:03.429277+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql
revision: str = 'a792650c543c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Not autogenerated — Alembic diffs tables, not extensions, so this is the
    # kind of thing you only get by reading the revision. Postgres 13+ has
    # gen_random_uuid() in core and does not need pgcrypto, but the column
    # defaults below name that function, and this makes the dependency explicit
    # rather than a property of whichever server version someone runs.
    op.execute('create extension if not exists "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversations_user_updated_idx', 'conversations', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_seconds >= 60', name='schedules_interval_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('schedules_due_idx', 'schedules', ['next_run_at'], unique=False, postgresql_where=sa.text('enabled'))
    op.create_table('event_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('user_message', 'assistant_message', 'tool_call', 'tool_result')", name='event_records_type_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('event_records_conversation_seq_idx', 'event_records', ['conversation_id', 'seq'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('chat_turn', 'agent_run')", name='tasks_kind_check'),
    sa.CheckConstraint("status in ('pending', 'running', 'succeeded', 'failed', 'cancelled', 'superseded')", name='tasks_status_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tasks_claim_idx', 'tasks', ['run_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('tasks_conversation_idx', 'tasks', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tasks_conversation_idx', table_name='tasks')
    op.drop_index('tasks_claim_idx', table_name='tasks', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('tasks')
    op.drop_index('event_records_conversation_seq_idx', table_name='event_records')
    op.drop_table('event_records')
    op.drop_index('schedules_due_idx', table_name='schedules', postgresql_where=sa.text('enabled'))
    op.drop_table('schedules')
    op.drop_index('conversations_user_updated_idx', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
